server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend-1.test-apps.svc.cluster.local:3001/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /angular/ {
        rewrite ^/angular/?(.*)$ /$1 break;
        try_files $uri /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
